name: Build xray-core
on:
  watch:
    types: started
  workflow_dispatch:

jobs:
  build-xray-core:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest

    steps:
    - name: Install UPX
      run: sudo apt-get install upx-ucl

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.25
        check-latest: true

    - name: Clone Xray-core Source
      run: |
        git clone https://github.com/XTLS/Xray-core
        cd Xray-core
        go mod download

    - name: Get Latest Release
      run: |
        RELEASE_TITLE=$(curl -s https://api.github.com/repos/XTLS/Xray-core/releases | jq -r 'first(.[]).name')
        echo "release_title=$RELEASE_TITLE" >> $GITHUB_ENV
        RELEASE_COMMITS=$(curl -s https://api.github.com/repos/XTLS/Xray-core/commits/main | grep -oP '"sha": "\K(.*)(?=")' | head -1)
        echo "release_commits=$RELEASE_COMMITS" >> $GITHUB_ENV
        echo "https://github.com/XTLS/Xray-core/commit/$RELEASE_COMMITS"

    - name: Build for AMD64
      run: |
        cd Xray-core
        go env -w CGO_ENABLED=0 GOOS=windows GOARCH=amd64
        go build -v -o xray-windows-amd64.exe -trimpath -ldflags "-s -w -buildid=" ./main
        tar -cJvf xray-windows-amd64.tar.xz xray-windows-amd64.exe
        echo "MD5= $(md5sum xray-linux-amd64.tar.xz | awk '{ print $1 }')" > xray-linux-amd64.tar.xz.dgst
        echo "SHA1= $(sha1sum xray-linux-amd64.tar.xz | awk '{ print $1 }')" >> xray-linux-amd64.tar.xz.dgst
        echo "SHA2-256= $(sha256sum xray-linux-amd64.tar.xz | awk '{ print $1 }')" >> xray-linux-amd64.tar.xz.dgst
        echo "SHA2-512= $(sha512sum xray-linux-amd64.tar.xz | awk '{ print $1 }')" >> xray-linux-amd64.tar.xz.dgst
        echo "MD5= $(md5sum xray-linux-amd64 | awk '{ print $1 }')" > xray-linux-amd64.dgst
        echo "SHA1= $(sha1sum xray-linux-amd64 | awk '{ print $1 }')" >> xray-linux-amd64.dgst
        echo "SHA2-256= $(sha256sum xray-linux-amd64 | awk '{ print $1 }')" >> xray-linux-amd64.dgst
        echo "SHA2-512= $(sha512sum xray-linux-amd64 | awk '{ print $1 }')" >> xray-linux-amd64.dgst

    - name: Build for AMD64v2
      run: |
        cd Xray-core
        go env -w CGO_ENABLED=0 GOOS=windows GOARCH=amd64 GOAMD64=v2
        go build -v -o xray-windows-amd64v2.exe -trimpath -ldflags "-s -w -buildid=" ./main
        tar -cJvf xray-windows-amd64v2.tar.xz xray-windows-amd64v2.exe
        echo "MD5= $(md5sum xray-linux-amd64v2.tar.xz | awk '{ print $1 }')" > xray-linux-amd64v2.tar.xz.dgst
        echo "SHA1= $(sha1sum xray-linux-amd64v2.tar.xz | awk '{ print $1 }')" >> xray-linux-amd64v2.tar.xz.dgst
        echo "SHA2-256= $(sha256sum xray-linux-amd64v2.tar.xz | awk '{ print $1 }')" >> xray-linux-amd64v2.tar.xz.dgst
        echo "SHA2-512= $(sha512sum xray-linux-amd64v2.tar.xz | awk '{ print $1 }')" >> xray-linux-amd64v2.tar.xz.dgst
        echo "MD5= $(md5sum xray-linux-amd64v2 | awk '{ print $1 }')" > xray-linux-amd64v2.dgst
        echo "SHA1= $(sha1sum xray-linux-amd64v2 | awk '{ print $1 }')" >> xray-linux-amd64v2.dgst
        echo "SHA2-256= $(sha256sum xray-linux-amd64v2 | awk '{ print $1 }')" >> xray-linux-amd64v2.dgst
        echo "SHA2-512= $(sha512sum xray-linux-amd64v2 | awk '{ print $1 }')" >> xray-linux-amd64v2.dgst

    - name: Build for AMD64v3
      run: |
        cd Xray-core
        go env -w CGO_ENABLED=0 GOOS=windows GOARCH=amd64 GOAMD64=v3
        go build -v -o xray-windows-amd64v3.exe -trimpath -ldflags "-s -w -buildid=" ./main
        tar -cJvf xray-windows-amd64v3.tar.xz xray-windows-amd64v3.exe
        echo "MD5= $(md5sum xray-linux-amd64v3.tar.xz | awk '{ print $1 }')" > xray-linux-amd64v3.tar.xz.dgst
        echo "SHA1= $(sha1sum xray-linux-amd64v3.tar.xz | awk '{ print $1 }')" >> xray-linux-amd64v3.tar.xz.dgst
        echo "SHA2-256= $(sha256sum xray-linux-amd64v3.tar.xz | awk '{ print $1 }')" >> xray-linux-amd64v3.tar.xz.dgst
        echo "SHA2-512= $(sha512sum xray-linux-amd64v3.tar.xz | awk '{ print $1 }')" >> xray-linux-amd64v3.tar.xz.dgst
        echo "MD5= $(md5sum xray-linux-amd64v3 | awk '{ print $1 }')" > xray-linux-amd64v3.dgst
        echo "SHA1= $(sha1sum xray-linux-amd64v3 | awk '{ print $1 }')" >> xray-linux-amd64v3.dgst
        echo "SHA2-256= $(sha256sum xray-linux-amd64v3 | awk '{ print $1 }')" >> xray-linux-amd64v3.dgst
        echo "SHA2-512= $(sha512sum xray-linux-amd64v3 | awk '{ print $1 }')" >> xray-linux-amd64v3.dgst

 
    - name: Delete current release assets
      uses: andreaswilli/delete-release-assets-action@v3.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag: latest
        deleteOnlyFromDrafts: false

    - name: Create and Upload Release
      id: upload_release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        release_name: ${{env.release_title}}
        tag: latest
        body: |
          Latest commit from the main branch:
          https://github.com/XTLS/Xray-core/commit/${{env.release_commits}}
        file_glob: true
        overwrite: true
        file: ./Xray-core/xray-*
